"""item change

Revision ID: 01f2e03f165a
Revises: a6f2d9b554b9
Create Date: 2023-04-22 05:23:44.169606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f2e03f165a'
down_revision = 'a6f2d9b554b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('availability',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('availability',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
