"""WD model upgate

Revision ID: 301bfa6be77b
Revises: ca34cc55cd94
Create Date: 2023-04-13 22:13:05.678617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301bfa6be77b'
down_revision = 'ca34cc55cd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_days_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekdayenum'), nullable=False),
    sa.Column('startWD_time', sa.Time(), nullable=False),
    sa.Column('finishWD_time', sa.Time(), nullable=False),
    sa.Column('period_time_panel', sa.Time(), nullable=False),
    sa.Column('hookah_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hookah_id'], ['hookahs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('worker_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_day',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('startWD_time', sa.TIME(), nullable=False),
    sa.Column('finishWD_time', sa.TIME(), nullable=False),
    sa.Column('period_time_panel', sa.TIME(), nullable=False),
    sa.Column('hookah_id', sa.INTEGER(), nullable=True),
    sa.Column('week_day', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['hookah_id'], ['hookahs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('worker_days_table')
    # ### end Alembic commands ###
