"""migrate change 2

Revision ID: 47798759aa57
Revises: ab6d1cc9a91b
Create Date: 2023-03-27 21:53:59.804131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47798759aa57'
down_revision = 'ab6d1cc9a91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekdayenum'), nullable=False))
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.INTEGER(), nullable=False))
        batch_op.drop_column('week_day')

    # ### end Alembic commands ###
