"""items, categories etc. menu stuff

Revision ID: a6f2d9b554b9
Revises: 301bfa6be77b
Create Date: 2023-04-20 22:57:03.899547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f2d9b554b9'
down_revision = '301bfa6be77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=25), nullable=False),
    sa.Column('category_description', sa.String(length=60), nullable=True),
    sa.Column('hookah_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hookah_id'], ['hookahs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_hookah_id'), ['hookah_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('item_description', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('archivation_date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('hookah_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hookah_id'], ['hookahs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_availability'), ['availability'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_hookah_id'), ['hookah_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_items_price'))
        batch_op.drop_index(batch_op.f('ix_items_is_archived'))
        batch_op.drop_index(batch_op.f('ix_items_hookah_id'))
        batch_op.drop_index(batch_op.f('ix_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_items_availability'))

    op.drop_table('items')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.drop_index(batch_op.f('ix_categories_hookah_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
