"""User, Hookah, Table, WorkTime model

Revision ID: ab6d1cc9a91b
Revises: 
Create Date: 2023-03-27 21:10:43.792214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6d1cc9a91b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hookahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_hookah', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_hookah')
    )
    with op.batch_alter_table('hookahs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hookahs_user_id'), ['user_id'], unique=False)

    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_of_persons', sa.String(), nullable=False),
    sa.Column('table_state', sa.String(), nullable=True),
    sa.Column('hookah_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hookah_id'], ['hookahs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_hookah_id'), ['hookah_id'], unique=False)

    op.create_table('worker_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('startWD_time', sa.Time(), nullable=False),
    sa.Column('finishWD_time', sa.Time(), nullable=False),
    sa.Column('period_time_panel', sa.Time(), nullable=False),
    sa.Column('hookah_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hookah_id'], ['hookahs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dt_booked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date_time_brooke', sa.DateTime(), nullable=False),
    sa.Column('finish_date_time_brooke', sa.DateTime(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dt_booked', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dt_booked_table_id'), ['table_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt_booked', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dt_booked_table_id'))

    op.drop_table('dt_booked')
    op.drop_table('worker_day')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_hookah_id'))

    op.drop_table('tables')
    with op.batch_alter_table('hookahs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hookahs_user_id'))

    op.drop_table('hookahs')
    # ### end Alembic commands ###
