"""DateTimeBooked model upgate

Revision ID: ee6d15126519
Revises: 301bfa6be77b
Create Date: 2023-04-19 19:32:43.815855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6d15126519'
down_revision = '301bfa6be77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt_booked', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookers_name', sa.String(), nullable=True))
        batch_op.alter_column('finish_date_time_brooke',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dt_booked', schema=None) as batch_op:
        batch_op.alter_column('finish_date_time_brooke',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('bookers_name')

    # ### end Alembic commands ###
